#
# This file is part of the FOSCommentBundle package.
#
# (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#
fos_comment_thread_api:
    type: rest
    resource: FOS\CommentBundle\Controller\ThreadController
    name_prefix: fos_comment_
